// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: wipe_db.sql

package database

import (
	"context"
)

const wipe = `-- name: Wipe :exec
DELETE FROM users
`

func (q *Queries) Wipe(ctx context.Context) error {
	_, err := q.db.ExecContext(ctx, wipe)
	return err
}
